# Brewfile — personal macOS setup
# Installed with: brew bundle --file=./Brewfile

# ---- Taps ----
tap "hudochenkov/sshpass"
tap "nextfire/tap"
tap "oven-sh/bun"

# ---- CLI tools & languages ----
brew "cliclick"
brew "cmake"
brew "dhcping"
brew "gh"
brew "git"
brew "go"
brew "hf"
brew "libomp"
brew "mole"
brew "ninja"
brew "nmap"
brew "node"
brew "ollama"
brew "poetry"
brew "poppler"
brew "python@3.13"
brew "subversion"
brew "swift-protobuf"
brew "tree"
brew "uv"
brew "wget"
brew "xcodegen"
brew "zig"

# ---- Apps (casks) ----
cask "1password"
cask "1password-cli"
cask "alcove"
cask "claude"
cask "docker-desktop"
cask "ghostty"
cask "linear-linear"
cask "mongodb-compass"
cask "notion"
cask "raycast"
cask "slack"
cask "wispr-flow"
cask "zed"
cask "zoom"
